version: '2.1'
orbs:
  python: circleci/python@3.0.0

jobs:
  build:
    executor:
      name: python/default
      tag: 3.13.1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: Compile Python files
          command: pipenv run python -m compileall main.py bot.py modules common -fq
#      - run:
#          name: Run tests
#          command: pipenv run pytest

workflows:
  main:
    jobs:
      - build
